# Generated by Django 5.1.5 on 2026-09-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Logged in'), ('LOGIN_2FA', 'Logged in with 2FA'), ('LOGOUT', 'Logged out'), ('REGISTER', 'Registered'), ('GOOGLE_FIRST_ACCOUNT', 'Google account created'), ('OTP_SENT', 'Email verification code sent'), ('OTP_RESENT', 'Email verification code resent'), ('OTP_VERIFIED', 'Email verified'), ('OTP_FAILED', 'Email verification failed'), ('OTP_EXPIRED', 'Email verification code expired'), ('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_EDITED', 'Reservation edited'), ('RESERVATION_APPROVED', 'Reservation approved'), ('RESERVATION_REJECTED', 'Reservation rejected'), ('RESERVATION_CANCELLED', 'Reservation cancelled'), ('RESERVATION_STATUS', 'Reservation status changed'), ('EARLY_CHECK_IN', 'Early check-in performed'), ('CHECK_IN', 'Checked in'), ('CHECK_OUT', 'Checked out'), ('EQUIPMENT_CREATED', 'Equipment created'), ('EQUIPMENT_EDITED', 'Equipment edited'), ('EQUIPMENT_REMOVED', 'Equipment removed'), ('EQUIPMENT_IMAGE', 'Equipment image changed'), ('FACILITY_CREATED', 'Facility created'), ('FACILITY_EDITED', 'Facility edited'), ('FACILITY_REMOVED', 'Facility removed'), ('SETTINGS_CHANGED', 'Settings changed')], max_length=32),
        ),
    ]
