# Generated by Django 5.1.5 on 2026-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login_verified',
            field=models.BooleanField(default=True),
        ),
    ]
