# Generated by Django 5.1.5 on 2026-09-25 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(blank=True, choices=[('NORSU_STUDENT', 'NORSU Student'), ('NORSU_FACULTY_STAFF', 'NORSU Faculty/Staff'), ('NORSU_OFFICE', 'NORSU Office/Department'), ('EXTERNAL_ORGANIZATION', 'External Organization')], db_index=True, default='', help_text='Blank = not yet chosen (treated as an internal campus user).', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Logged in'), ('LOGIN_2FA', 'Logged in with 2FA'), ('LOGOUT', 'Logged out'), ('REGISTER', 'Registered'), ('GOOGLE_FIRST_ACCOUNT', 'Google account created'), ('OTP_SENT', 'Email verification code sent'), ('OTP_RESENT', 'Email verification code resent'), ('OTP_VERIFIED', 'Email verified'), ('OTP_FAILED', 'Email verification failed'), ('OTP_EXPIRED', 'Email verification code expired'), ('RESERVATION_CREATED', 'Reservation created'), ('RESERVATION_EDITED', 'Reservation edited'), ('RESERVATION_APPROVED', 'Reservation approved'), ('RESERVATION_REJECTED', 'Reservation rejected'), ('RESERVATION_CANCELLED', 'Reservation cancelled'), ('RESERVATION_STATUS', 'Reservation status changed'), ('EARLY_CHECK_IN', 'Early check-in performed'), ('CHECK_IN', 'Checked in'), ('CHECK_OUT', 'Checked out'), ('EQUIPMENT_CREATED', 'Equipment created'), ('EQUIPMENT_EDITED', 'Equipment edited'), ('EQUIPMENT_REMOVED', 'Equipment removed'), ('EQUIPMENT_IMAGE', 'Equipment image changed'), ('FACILITY_CREATED', 'Facility created'), ('FACILITY_EDITED', 'Facility edited'), ('FACILITY_REMOVED', 'Facility removed'), ('FACILITY_IMAGE', 'Facility image changed'), ('SETTINGS_CHANGED', 'Settings changed'), ('AFFILIATION_CHANGED', 'Affiliation changed'), ('ORGANIZATION_REGISTERED', 'Organization registered'), ('ORGANIZATION_UPDATED', 'Organization updated'), ('ORGANIZATION_APPROVED', 'Organization approved'), ('ORGANIZATION_REJECTED', 'Organization rejected'), ('ORGANIZATION_SUSPENDED', 'Organization suspended'), ('ORGANIZATION_REACTIVATED', 'Organization reactivated')], max_length=32),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_code', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('organization_name', models.CharField(max_length=160)),
                ('organization_type', models.CharField(choices=[('GOVERNMENT_AGENCY', 'Government Agency'), ('NGO', 'NGO'), ('PRIVATE_ORGANIZATION', 'Private Organization'), ('COMMUNITY_ORGANIZATION', 'Community Organization'), ('SCHOOL_UNIVERSITY', 'School/University'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('contact_person', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('purpose', models.TextField(blank=True, help_text='Why the organization needs to use NORSU facilities.')),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'external organization',
                'verbose_name_plural': 'external organizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization_ref',
            field=models.ForeignKey(blank=True, help_text='External organization this user belongs to. Set only through the backend from the authenticated user — never from a client-sent id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['verification_status', 'organization_type'], name='accounts_or_verific_7ab4c3_idx'),
        ),
    ]
