# Generated by Django 5.1.5 on 2026-10-01 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_affiliation_alter_auditlog_action_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['-created_at'], 'verbose_name': 'organization', 'verbose_name_plural': 'organizations'},
        ),
        migrations.AddField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Short code for internal organizations (e.g. CAS).', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Inactive organizations cannot be selected or used on new reservations.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal Organization'), ('GOVERNMENT_AGENCY', 'Government Agency'), ('NGO', 'NGO'), ('PRIVATE_ORGANIZATION', 'Private Organization'), ('COMMUNITY_ORGANIZATION', 'Community Organization'), ('SCHOOL_UNIVERSITY', 'School/University'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization_ref',
            field=models.ForeignKey(blank=True, help_text='Organization this user belongs to (internal NORSU college/office or external organization). Set only through the backend from the authenticated user — never from a client-sent id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('acronym', ''), _negated=True), fields=('acronym',), name='unique_organization_acronym'),
        ),
    ]
