# Generated by Django 6.1.1 on 2026-09-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='asset_code',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under Maintenance'), ('UNAVAILABLE', 'Unavailable'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=16),
        ),
        migrations.AddField(
            model_name='equipment',
            name='unit',
            field=models.CharField(default='unit', max_length=40),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=16),
        ),
    ]
