# Generated by Django 5.1.5 on 2026-09-27 02:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_copy_legacy_equipment_images'),
        ('facilities', '0003_copy_legacy_facility_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text="Units of this resource available at this facility. 0 = inherit the equipment's total inventory.")),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=16)),
                ('additional_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-unit fee for external organizations at this facility. 0 = no additional fee (this overrides any category rate).', max_digits=12)),
                ('operator_available', models.BooleanField(default=False, help_text='Whether the requester may opt in to an operator/service for this resource.')),
                ('operator_required', models.BooleanField(default=False, help_text='When true the operator service fee is always charged for this resource.')),
                ('operator_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat service fee for the operator, charged when selected/required.', max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignments', to='equipment.equipment')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_resources', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'facility resource',
                'verbose_name_plural': 'facility resources',
                'ordering': ['display_order', 'equipment__name'],
                'indexes': [models.Index(fields=['facility', 'is_active'], name='equipment_f_facilit_8b93f4_idx')],
                'constraints': [models.UniqueConstraint(fields=('facility', 'equipment'), name='unique_facility_resource')],
            },
        ),
    ]
