# Generated by Django 5.1.5 on 2026-09-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_facilityresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityresource',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Under Maintenance'), ('DAMAGED', 'Damaged')], default='AVAILABLE', max_length=16),
        ),
    ]
