# Generated by Django 5.1.5 on 2026-09-29 02:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_facilityresource_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityresource',
            name='additional_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-unit fee for external organizations at this facility. 0 = use the configured per-category rate (no override).', max_digits=12),
        ),
    ]
