# Generated by Django 5.1.5 on 2026-10-07 05:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_facilityresource_additional_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per-unit price used when pricing reservations. 0 = use the configured per-category rate (no item override).', max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='equipment_price_nonnegative'),
        ),
    ]
