# Generated by Django 5.1.5 on 2026-10-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_equipment_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='unit',
            field=models.CharField(choices=[('unit', 'Unit'), ('piece', 'Piece'), ('set', 'Set'), ('pair', 'Pair'), ('box', 'Box')], default='unit', max_length=40),
        ),
    ]
