# Generated by Django 6.1.1 on 2026-09-05 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('facility_type', models.CharField(choices=[('GYMNASIUM', 'Gymnasium'), ('CAFETERIA', 'Cafeteria'), ('AVR', 'Audio-Visual Room'), ('MULTI_PURPOSE', 'Multi-Purpose Hall'), ('OUTDOOR', 'Outdoor Area'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('image', models.ImageField(blank=True, null=True, upload_to='facilities/')),
                ('rules', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('MAINTENANCE', 'Under Maintenance')], default='OPERATIONAL', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='facilities.facility')),
            ],
            options={
                'ordering': ['day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'day_of_week'), name='unique_facility_day')],
            },
        ),
    ]
