# Generated by Django 5.1.5 on 2026-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_copy_legacy_facility_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='seating_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('tables_and_chairs', 'Tables and chairs'),
                    ('fixed_rows', 'Fixed rows'),
                    ('open_floor', 'Open floor'),
                ],
                default=None,
                help_text='How the space is seated. Leave empty when unverified.',
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='facility',
            name='built_in_seats',
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text=(
                    'Seats the space already provides at tables/fixed rows. Leave '
                    'empty when it has no fixed seating or is unverified.'
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='facility',
            name='built_ins',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    'Items the space already provides, e.g. '
                    '["tables", "chairs", "projector", "sound_system", "stage", "podium"].'
                ),
            ),
        ),
    ]
