# Generated by Django 6.1.1 on 2026-09-05 03:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('organization', models.CharField(blank=True, max_length=120)),
                ('event_name', models.CharField(max_length=160)),
                ('event_type', models.CharField(choices=[('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural'), ('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('OTHER', 'Other')], default='OTHER', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('expected_participants', models.PositiveIntegerField(default=0)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('checkin_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='facilities.facility')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged')], default='GOOD', max_length=16)),
                ('equipment_returned', models.BooleanField(default=False)),
                ('missing_items', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='inspections/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reports', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested'), ('CANCELLED', 'Cancelled'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('COMMENT', 'Comment')], max_length=32)),
                ('from_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('to_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=16)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_events', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='reservations.reservation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('returned', models.BooleanField(default=False)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_items', to='equipment.equipment')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reservations.reservation')),
            ],
            options={
                'ordering': ['equipment__name'],
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['date', 'status'], name='reservation_date_b616a1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['facility', 'date'], name='reservation_facilit_f51f34_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservationitem',
            constraint=models.UniqueConstraint(fields=('reservation', 'equipment'), name='unique_reservation_equipment'),
        ),
    ]
