# Generated by Django 6.1.1 on 2026-09-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event_type',
            field=models.CharField(choices=[('SEMINAR', 'Seminar'), ('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('TRAINING', 'Training'), ('SPORTS', 'Sports Event'), ('CONFERENCE', 'Conference'), ('RECOGNITION', 'Recognition Program'), ('ORIENTATION', 'Orientation'), ('CULTURAL', 'Cultural Event'), ('ACADEMIC', 'Academic Event'), ('OTHER', 'Other')], default='OTHER', max_length=32),
        ),
    ]
