# Generated by Django 5.1.5 on 2026-09-06 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('reservations', '0002_reservation_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='For external requesters, this doubles as the tracking verification field (reservation code + email).', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='contact_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Account that entered the reservation into the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='early_check_in_override',
            field=models.BooleanField(default=False, help_text='True when an administrator checked the reservation in before the standard 3-hour window.'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'School'), ('GOVERNMENT', 'Government Organization'), ('PRIVATE', 'Private Organization'), ('COMMUNITY', 'Community Organization'), ('SPORTS', 'Sports Organization'), ('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual'), ('OTHER', 'Other')], help_text='For external requesters: what kind of organization they are.', max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='requester_type',
            field=models.CharField(choices=[('CAMPUS', 'Campus User'), ('EXTERNAL', 'External Organization')], db_index=True, default='CAMPUS', max_length=16),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='requester',
            field=models.ForeignKey(blank=True, help_text='Account of the requester. Null for external requesters who do not have accounts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['requester_type', 'status'], name='reservation_request_30d3d4_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['contact_email'], name='reservation_contact_79c8c1_idx'),
        ),
    ]
