# Generated by Django 5.1.5 on 2026-09-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_approved_at_reservation_approved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='contact_number',
        ),
    ]
