# Generated by Django 5.1.5 on 2026-09-11 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_asset_code_equipment_image_equipment_notes_and_more'),
        ('reservations', '0004_remove_contact_number_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, help_text='Leave blank to apply to all event types.', max_length=32)),
                ('facility_type', models.CharField(blank=True, help_text='Leave blank to apply to all facility types.', max_length=32)),
                ('min_participants', models.PositiveIntegerField(default=0, help_text='Rule applies when participants >= this value.')),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Rule applies when participants <= this value. Blank = no upper limit.', null=True)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed quantity'), ('PER_PARTICIPANT', 'Units per participant'), ('PER_GROUP', 'Units per group of participants'), ('THRESHOLD', 'Threshold tiers')], default='PER_GROUP', max_length=20)),
                ('quantity_value', models.PositiveIntegerField(default=1, help_text='Meaning depends on the calculation type: fixed quantity, multiplier per participant, or units per group.')),
                ('participants_per_unit', models.PositiveIntegerField(default=10, help_text="For 'units per group': one unit covers this many participants (ceiling division).")),
                ('threshold_tier_1', models.PositiveIntegerField(blank=True, help_text='Threshold tiers: participants <= tier 1 → tier 1 quantity.', null=True)),
                ('threshold_quantity_1', models.PositiveIntegerField(blank=True, null=True)),
                ('threshold_tier_2', models.PositiveIntegerField(blank=True, help_text='Threshold tiers: participants <= tier 2 → tier 2 quantity.', null=True)),
                ('threshold_quantity_2', models.PositiveIntegerField(blank=True, null=True)),
                ('threshold_quantity_3', models.PositiveIntegerField(blank=True, help_text="Threshold tiers: quantity when participants exceed tier 2. Blank = use 'Fixed quantity' value.", null=True)),
                ('priority', models.IntegerField(default=100, help_text='Tie-breaker when several rules match: lower number wins.')),
                ('explanation', models.CharField(blank=True, help_text="Custom reason shown to requesters, e.g. '1 table per 10 participants, rounded up'. Leave blank to auto-generate one.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Equipment category this rule recommends.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_rules', to='equipment.equipmentcategory')),
            ],
            options={
                'ordering': ['priority', 'id'],
                'indexes': [models.Index(fields=['event_type', 'facility_type'], name='reservation_event_t_8e661e_idx'), models.Index(fields=['is_active'], name='reservation_is_acti_1ddb4e_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_participants__lt', 0), _negated=True), name='recommendation_rule_min_participants_nonnegative'), models.CheckConstraint(condition=models.Q(models.Q(('max_participants__isnull', True), ('max_participants__gte', models.F('min_participants')), _connector='OR')), name='recommendation_rule_participant_range_valid'), models.CheckConstraint(condition=models.Q(('participants_per_unit__gte', 1)), name='recommendation_rule_group_size_positive')],
            },
        ),
    ]
