# Generated by Django 5.1.5 on 2026-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_recommendationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationrule',
            name='min_participants',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Rule applies when participants >= this value. Leave empty for no minimum.'),
        ),
    ]
