# Generated by Django 5.1.5 on 2026-09-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_recommendationrule_min_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approval_email_status',
            field=models.CharField(choices=[('NOT_SENT', 'Not sent'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('NO_EMAIL', 'No requester email')], default='NOT_SENT', help_text='Delivery state of the approval notification email (staff diagnostic).', max_length=16),
        ),
    ]
