# Generated by Django 5.1.5 on 2026-09-25 10:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_copy_legacy_equipment_images'),
        ('reservations', '0007_reservation_approval_email_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='estimated_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ReservationFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('FACILITY', 'Facility'), ('EQUIPMENT', 'Equipment'), ('OPERATOR', 'Operator')], max_length=16)),
                ('description', models.CharField(max_length=160)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=32)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='reservations.reservation')),
            ],
            options={
                'ordering': ['fee_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('FACILITY', 'Facility fee'), ('EQUIPMENT', 'Equipment fee'), ('OPERATOR', 'Operator fee')], db_index=True, max_length=16)),
                ('facility_type', models.CharField(blank=True, choices=[('GYMNASIUM', 'Gymnasium'), ('CAFETERIA', 'Cafeteria'), ('AVR', 'Audio-Visual Room'), ('MULTI_PURPOSE', 'Multi-Purpose Hall'), ('OUTDOOR', 'Outdoor Area'), ('OTHER', 'Other')], help_text='For facility fees: which facility type this rate covers.', max_length=32)),
                ('label', models.CharField(blank=True, help_text="Name shown on the fee breakdown, e.g. 'Gymnasium' or 'Sound System Operator'.", max_length=120)),
                ('unit', models.CharField(choices=[('flat', 'Flat per reservation'), ('unit', 'Per unit'), ('hour', 'Per hour')], default='unit', help_text='How the price is charged: flat, per unit, or per hour.', max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_category', models.ForeignKey(blank=True, help_text='For equipment/operator fees: the category this rate applies to (and, for operator fees, the category that triggers the fee).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='equipment.equipmentcategory')),
            ],
            options={
                'ordering': ['fee_type', 'facility_type', 'equipment_category__name'],
                'indexes': [models.Index(fields=['fee_type', 'is_active'], name='reservation_fee_typ_80715c_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='pricing_rule_unit_price_nonnegative')],
            },
        ),
    ]
