# Generated by Django 5.1.5 on 2026-09-25 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_affiliation_alter_auditlog_action_organization_and_more'),
        ('reservations', '0009_default_pricing_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='organization_ref',
            field=models.ForeignKey(blank=True, help_text='Verified external organization this reservation belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_reservations', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'School'), ('GOVERNMENT', 'Government Organization'), ('PRIVATE', 'Private Organization'), ('COMMUNITY', 'Community Organization'), ('NGO', 'Non-Governmental Organization'), ('SPORTS', 'Sports Organization'), ('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual'), ('OTHER', 'Other')], help_text='For external requesters: what kind of organization they are.', max_length=32),
        ),
    ]
