# Generated by Django 5.1.5 on 2026-09-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_pricing_overtime_included_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationitem',
            name='operator_requested',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
