# Generated by Django 5.1.5 on 2026-10-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_reservationitem_operator_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
