# Generated by Django 5.1.5 on 2026-10-06 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_reservation_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='rebooked_from',
            field=models.ForeignKey(blank=True, help_text='Expired reservation this one was created from (rebook / request new schedule).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebookings', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='reservationevent',
            name='event_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested'), ('CANCELLED', 'Cancelled'), ('CHECKED_IN', 'Checked in'), ('CHECKED_OUT', 'Checked out'), ('COMMENT', 'Comment'), ('EXPIRED', 'Expired'), ('REBOOKED', 'Rebooked'), ('NEW_SCHEDULE_REQUESTED', 'New schedule requested')], max_length=32),
        ),
        migrations.AlterField(
            model_name='reservationevent',
            name='from_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=16),
        ),
        migrations.AlterField(
            model_name='reservationevent',
            name='to_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=16),
        ),
    ]
