# Generated by Django 5.1.5 on 2026-09-16 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=40)),
                ('confidence', models.CharField(blank=True, max_length=16)),
                ('entities', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, choices=[('database', 'Live database'), ('knowledge', 'Knowledge base'), ('hybrid', 'Database + knowledge base'), ('help', 'Help/capabilities'), ('fallback', 'Fallback')], max_length=16)),
                ('retrieved_refs', models.JSONField(blank=True, default=list)),
                ('response', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESERVATION_POLICY', 'Reservation Policy'), ('CANCELLATION_POLICY', 'Cancellation Policy'), ('FACILITY_RULES', 'Facility Rules'), ('BOOKING_GUIDE', 'Booking Instructions'), ('FAQ', 'Frequently Asked Questions'), ('GENERAL', 'General Information')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.CharField(blank=True, help_text='Comma or space separated keywords for matching user questions.', max_length=500)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='PUBLISHED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entries', to='facilities.facility')),
            ],
            options={
                'ordering': ['category', 'title'],
                'indexes': [models.Index(fields=['category', 'status'], name='chatbot_kno_categor_3343c8_idx')],
            },
        ),
    ]
