# Generated by Django 5.1.5 on 2026-09-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseentry',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('AUTHENTICATED', 'Authenticated only'), ('ADMIN', 'Administrators only')], default='PUBLIC', max_length=16),
        ),
        migrations.AlterField(
            model_name='knowledgebaseentry',
            name='category',
            field=models.CharField(choices=[('RESERVATION_POLICY', 'Reservation Policy'), ('CANCELLATION_POLICY', 'Cancellation Policy'), ('FACILITY_RULES', 'Facility Rules'), ('BOOKING_GUIDE', 'Booking Instructions'), ('REGISTRATION_HELP', 'Registration Help'), ('LOGIN_HELP', 'Login Help'), ('ANNOUNCEMENT', 'Announcement'), ('FAQ', 'Frequently Asked Questions'), ('GENERAL', 'General Information')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='knowledgebaseentry',
            index=models.Index(fields=['visibility', 'status'], name='chatbot_kno_visibil_f6160c_idx'),
        ),
    ]
